In [0]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [0]:
dataset=pd.read_csv('sliding02_goals.csv')
y= dataset.iloc[:,1:3].values
X= dataset.iloc[:,3:].values


In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2, random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.fit_transform(X_test)

In [0]:
ann= tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=2))

In [0]:
ann.compile(optimizer='adam',loss='mean_squared_error',metrics=[tf.keras.metrics.RootMeanSquaredError()])

In [0]:
ann.fit(X_train,y_train,batch_size=100,epochs=20)

Epoch 1/20
57/57 [==============================] - 0s 2ms/step - loss: 2.4812 - root_mean_squared_error: 1.5752
Epoch 2/20
57/57 [==============================] - 0s 1ms/step - loss: 1.6876 - root_mean_squared_error: 1.2991
Epoch 3/20
57/57 [==============================] - 0s 2ms/step - loss: 1.5345 - root_mean_squared_error: 1.2388
Epoch 4/20
57/57 [==============================] - 0s 2ms/step - loss: 1.4827 - root_mean_squared_error: 1.2176
Epoch 5/20
57/57 [==============================] - 0s 2ms/step - loss: 1.4517 - root_mean_squared_error: 1.2048
Epoch 6/20
57/57 [==============================] - 0s 1ms/step - loss: 1.4298 - root_mean_squared_error: 1.1957
Epoch 7/20
57/57 [==============================] - 0s 1ms/step - loss: 1.4140 - root_mean_squared_error: 1.1891
Epoch 8/20
57/57 [==============================] - 0s 1ms/step - loss: 1.4005 - root_mean_squared_error: 1.1834
Epoch 9/20
57/57 [==============================] - 0s 1ms/step - loss: 1.3888 - root_mean_squar

In [0]:
y_pred= ann.predict(X_test)
y_pred=(y_pred>0.5)

In [0]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2),y_test.reshape(len(y_test),2)),1))

[[1.91 0.85 2.   3.  ]
 [0.89 1.57 2.   2.  ]
 [1.97 0.81 2.   2.  ]
 ...
 [1.71 1.29 1.   2.  ]
 [1.36 1.25 2.   0.  ]
 [1.43 1.03 1.   3.  ]]


#USING MEAN_SQUARED_LOGARITHMIC_ERROR

In [0]:
ann.compile(optimizer='adam',loss='mean_squared_logarithmic_error',metrics='accuracy')

In [9]:
ann.fit(X_train,y_train,batch_size=100,epochs=20)

Epoch 1/20
57/57 [==============================] - 0s 2ms/step - loss: 0.2451 - accuracy: 0.7110
Epoch 2/20
57/57 [==============================] - 0s 1ms/step - loss: 0.2445 - accuracy: 0.7140
Epoch 3/20
57/57 [==============================] - 0s 1ms/step - loss: 0.2441 - accuracy: 0.7138
Epoch 4/20
57/57 [==============================] - 0s 1ms/step - loss: 0.2436 - accuracy: 0.7117
Epoch 5/20
57/57 [==============================] - 0s 2ms/step - loss: 0.2434 - accuracy: 0.7169
Epoch 6/20
57/57 [==============================] - 0s 2ms/step - loss: 0.2431 - accuracy: 0.7128
Epoch 7/20
57/57 [==============================] - 0s 2ms/step - loss: 0.2430 - accuracy: 0.7128
Epoch 8/20
57/57 [==============================] - 0s 2ms/step - loss: 0.2426 - accuracy: 0.7144
Epoch 9/20
57/57 [==============================] - 0s 2ms/step - loss: 0.2424 - accuracy: 0.7138
Epoch 10/20
57/57 [==============================] - 0s 2ms/step - loss: 0.2422 - accuracy: 0.7135
Epoch 11/20
57/57 [

In [11]:
y_pred= ann.predict(X_test)
y_pred=(y_pred>0.5)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2),y_test.reshape(len(y_test),2)),1))

[[1 1 2 3]
 [1 1 2 2]
 [1 1 2 2]
 ...
 [1 1 1 2]
 [1 1 2 0]
 [1 1 1 3]]


#Mean Absolute Error Loss

In [13]:
ann.compile(optimizer='adam',loss='mean_absolute_error',metrics=[tf.keras.metrics.RootMeanSquaredError()])
ann.fit(X_train,y_train,batch_size=100,epochs=20)
y_pred= ann.predict(X_test)
y_pred=(y_pred>0.5)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2),y_test.reshape(len(y_test),2)),1))

Epoch 1/20
57/57 [==============================] - 0s 1ms/step - loss: 0.8736 - root_mean_squared_error: 1.1632
Epoch 2/20
57/57 [==============================] - 0s 1ms/step - loss: 0.8729 - root_mean_squared_error: 1.1623
Epoch 3/20
57/57 [==============================] - 0s 1ms/step - loss: 0.8723 - root_mean_squared_error: 1.1610
Epoch 4/20
57/57 [==============================] - 0s 2ms/step - loss: 0.8725 - root_mean_squared_error: 1.1615
Epoch 5/20
57/57 [==============================] - 0s 1ms/step - loss: 0.8720 - root_mean_squared_error: 1.1624
Epoch 6/20
57/57 [==============================] - 0s 2ms/step - loss: 0.8718 - root_mean_squared_error: 1.1617
Epoch 7/20
57/57 [==============================] - 0s 2ms/step - loss: 0.8714 - root_mean_squared_error: 1.1605
Epoch 8/20
57/57 [==============================] - 0s 2ms/step - loss: 0.8710 - root_mean_squared_error: 1.1616
Epoch 9/20
57/57 [==============================] - 0s 2ms/step - loss: 0.8715 - root_mean_squar