In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf


In [0]:
df= pd.read_csv('https://raw.githubusercontent.com/Khaledjallouli/project/master/data/data_regression_goals/sliding02_goals.csv')

In [112]:
df.head()

Unnamed: 0  ...  away-opposition_shots_on_target
0           0  ...                               30
1           1  ...                               36
2           2  ...                               46
3           3  ...                               58
4           4  ...                               69

[5 rows x 24 columns]

In [0]:
X= df.iloc[:,3:-1].values
y= df.iloc[:,1:3].values

In [114]:
print(X)

[[  3.5    3.3    2.1  ... 161.    78.    72.  ]
 [  2.5    3.3    2.88 ... 104.    44.    87.  ]
 [  1.91   3.4    4.2  ... 134.    59.   100.  ]
 ...
 [  1.8    3.75   4.5  ...  84.    43.   118.  ]
 [  1.33   5.25   9.   ... 103.    53.   122.  ]
 [  1.67   4.2    5.25 ... 114.    63.   106.  ]]


In [115]:
print(y)

[[2 1]
 [2 2]
 [1 2]
 ...
 [4 1]
 [3 1]
 [3 1]]


In [116]:
for index_home in range( len(y) ):
  for index_away in range (len(y[index_home])):
    if y[index_home][index_away] >=5:
      y[index_home][index_away]=5
print(y)    

[[2 1]
 [2 2]
 [1 2]
 ...
 [4 1]
 [3 1]
 [3 1]]


In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2, random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [0]:
ann= tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10,activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))
ann.add(tf.keras.layers.Dense(units=2))

In [0]:
ann.compile(optimizer='adam',loss='mean_squared_error',metrics=[tf.keras.metrics.RootMeanSquaredError(),'accuracy'])

In [121]:
ann.fit(X_train,y_train,batch_size=100,epochs=20)

Epoch 1/20
57/57 [==============================] - 0s 1ms/step - loss: 2.9672 - root_mean_squared_error: 1.7226 - accuracy: 0.6845
Epoch 2/20
57/57 [==============================] - 0s 1ms/step - loss: 2.1702 - root_mean_squared_error: 1.4732 - accuracy: 0.6994
Epoch 3/20
57/57 [==============================] - 0s 1ms/step - loss: 1.6350 - root_mean_squared_error: 1.2787 - accuracy: 0.7007
Epoch 4/20
57/57 [==============================] - 0s 1ms/step - loss: 1.4291 - root_mean_squared_error: 1.1955 - accuracy: 0.7019
Epoch 5/20
57/57 [==============================] - 0s 1ms/step - loss: 1.3763 - root_mean_squared_error: 1.1731 - accuracy: 0.7064
Epoch 6/20
57/57 [==============================] - 0s 1ms/step - loss: 1.3482 - root_mean_squared_error: 1.1611 - accuracy: 0.7112
Epoch 7/20
57/57 [==============================] - 0s 1ms/step - loss: 1.3286 - root_mean_squared_error: 1.1526 - accuracy: 0.7105
Epoch 8/20
57/57 [==============================] - 0s 1ms/step - loss: 1.31

In [0]:
y_pred= ann.predict(X_test)

In [123]:
print(y_pred)

[[2.12 0.76]
 [1.14 1.5 ]
 [1.77 0.88]
 ...
 [1.75 1.23]
 [1.57 1.27]
 [1.37 0.88]]


In [124]:
print(y_test)

[[2 3]
 [2 2]
 [2 2]
 ...
 [1 2]
 [2 0]
 [1 3]]


In [125]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),2),y_test.reshape(len(y_test),2)),1))

[[2.12 0.76 2.   3.  ]
 [1.14 1.5  2.   2.  ]
 [1.77 0.88 2.   2.  ]
 ...
 [1.75 1.23 1.   2.  ]
 [1.57 1.27 2.   0.  ]
 [1.37 0.88 1.   3.  ]]
